mimetypes = {
    "file": "application/vnd.google-apps.file",
    "folder": "application/vnd.google-apps.folder",
    "audio": "application/vnd.google-apps.audio",
    "doc": "application/vnd.google-apps.document",
    "drawing": "application/vnd.google-apps.drawing",
    "form": "application/vnd.google-apps.form",
    "fusion_table": "application/vnd.google-apps.fusiontable",
    "map": "application/vnd.google-apps.map",
    "photo": "application/vnd.google-apps.photo",
    "slide": "application/vnd.google-apps.presentation",
    "apps_script": "application/vnd.google-apps.script",
    "shortcut": "application/vnd.google-apps.shortcut",
    "site": "application/vnd.google-apps.site",
    "spreadsheet": "application/vnd.google-apps.spreadsheet",
    "unknown": "application/vnd.google-apps.unknown",
    "video": "application/vnd.google-apps.video",
    "drive_sdk": "application/vnd.google-apps.drive-sdk",
}
