# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_subscription', '0003_auto_20200825_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gendermember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Member gender')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'control'),
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_subscription.Gendermember'),
        ),
        migrations.AlterField(
            model_name='typemember',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Type of member'),
        ),
    ]
