
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-23T13:46:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0ea1b8e628dc2f48bc9d88a9283bffa00c75656",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
