# coding: utf-8

"""
    VeeRoute.LSS Lastmile

    VeeRoute.LSS Lastmile API  # noqa: E501

    The version of the OpenAPI document: 3.6.163884
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vrt_lss_lastmile
from vrt_lss_lastmile.api.validate_api import ValidateApi  # noqa: E501
from vrt_lss_lastmile.rest import ApiException


class TestValidateApi(unittest.TestCase):
    """ValidateApi unit test stubs"""

    def setUp(self):
        self.api = vrt_lss_lastmile.api.validate_api.ValidateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_validate(self):
        """Test case for validate

        Data validation for planning.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
