/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.24
 *
 *     Copyright: (c) 2020 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_propgrid.h"

        #include <wx/propgrid/editors.h>

        #include <wx/window.h>
        #include <wx/propgrid/propgrid.h>
        #include <wx/propgrid/property.h>
        #include <wx/gdicmn.h>
        #include <wx/gdicmn.h>
        #include <wx/event.h>
        #include <wx/propgrid/editors.h>
        #include <wx/propgrid/property.h>
        #include <wx/dc.h>
        #include <wx/gdicmn.h>
        #include <wx/object.h>
        #include <wx/object.h>
        #include <wx/object.h>


class sipwxPGChoiceEditor : public  ::wxPGChoiceEditor
{
public:
    sipwxPGChoiceEditor();
    sipwxPGChoiceEditor(const  ::wxPGChoiceEditor&);
    virtual ~sipwxPGChoiceEditor();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    bool GetValueFromControl( ::wxPGVariant&, ::wxPGProperty*, ::wxWindow*) const SIP_OVERRIDE;
     ::wxString GetName() const SIP_OVERRIDE;
     ::wxPGWindowList CreateControls( ::wxPropertyGrid*, ::wxPGProperty*,const  ::wxPoint&,const  ::wxSize&) const SIP_OVERRIDE;
    void UpdateControl( ::wxPGProperty*, ::wxWindow*) const SIP_OVERRIDE;
    void DrawValue( ::wxDC&,const  ::wxRect&, ::wxPGProperty*,const  ::wxString&) const SIP_OVERRIDE;
    bool OnEvent( ::wxPropertyGrid*, ::wxPGProperty*, ::wxWindow*, ::wxEvent&) const SIP_OVERRIDE;
    void SetValueToUnspecified( ::wxPGProperty*, ::wxWindow*) const SIP_OVERRIDE;
    void SetControlAppearance( ::wxPropertyGrid*, ::wxPGProperty*, ::wxWindow*,const  ::wxPGCell&,const  ::wxPGCell&,bool) const SIP_OVERRIDE;
    void SetControlStringValue( ::wxPGProperty*, ::wxWindow*,const  ::wxString&) const SIP_OVERRIDE;
    void SetControlIntValue( ::wxPGProperty*, ::wxWindow*,int) const SIP_OVERRIDE;
    int InsertItem( ::wxWindow*,const  ::wxString&,int) const SIP_OVERRIDE;
    void DeleteItem( ::wxWindow*,int) const SIP_OVERRIDE;
    void OnFocus( ::wxPGProperty*, ::wxWindow*) const SIP_OVERRIDE;
    bool CanContainCustomImage() const SIP_OVERRIDE;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipwxPGChoiceEditor(const sipwxPGChoiceEditor &);
    sipwxPGChoiceEditor &operator = (const sipwxPGChoiceEditor &);

    char sipPyMethods[14];
};

sipwxPGChoiceEditor::sipwxPGChoiceEditor():  ::wxPGChoiceEditor(), sipPySelf(SIP_NULLPTR)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxPGChoiceEditor::sipwxPGChoiceEditor(const  ::wxPGChoiceEditor& a0):  ::wxPGChoiceEditor(a0), sipPySelf(SIP_NULLPTR)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxPGChoiceEditor::~sipwxPGChoiceEditor()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

bool sipwxPGChoiceEditor::GetValueFromControl( ::wxPGVariant& variant, ::wxPGProperty*property, ::wxWindow*ctrl) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,SIP_NULLPTR,sipName_GetValueFromControl);

    if (!sipMeth)
        return  ::wxPGChoiceEditor::GetValueFromControl(variant,property,ctrl);

    extern bool sipVH__propgrid_34(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPGVariant&, ::wxPGProperty*, ::wxWindow*);

    return sipVH__propgrid_34(sipGILState, 0, sipPySelf, sipMeth, variant, property, ctrl);
}

 ::wxString sipwxPGChoiceEditor::GetName() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[1]),sipPySelf,SIP_NULLPTR,sipName_GetName);

    if (!sipMeth)
        return  ::wxPGChoiceEditor::GetName();

    extern  ::wxString sipVH__propgrid_22(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH__propgrid_22(sipGILState, 0, sipPySelf, sipMeth);
}

 ::wxPGWindowList sipwxPGChoiceEditor::CreateControls( ::wxPropertyGrid*propgrid, ::wxPGProperty*property,const  ::wxPoint& pos,const  ::wxSize& size) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[2]),sipPySelf,SIP_NULLPTR,sipName_CreateControls);

    if (!sipMeth)
        return  ::wxPGChoiceEditor::CreateControls(propgrid,property,pos,size);

    extern  ::wxPGWindowList sipVH__propgrid_23(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPropertyGrid*, ::wxPGProperty*,const  ::wxPoint&,const  ::wxSize&);

    return sipVH__propgrid_23(sipGILState, 0, sipPySelf, sipMeth, propgrid, property, pos, size);
}

void sipwxPGChoiceEditor::UpdateControl( ::wxPGProperty*property, ::wxWindow*ctrl) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[3]),sipPySelf,SIP_NULLPTR,sipName_UpdateControl);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::UpdateControl(property,ctrl);
        return;
    }

    extern void sipVH__propgrid_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPGProperty*, ::wxWindow*);

    sipVH__propgrid_24(sipGILState, 0, sipPySelf, sipMeth, property, ctrl);
}

void sipwxPGChoiceEditor::DrawValue( ::wxDC& dc,const  ::wxRect& rect, ::wxPGProperty*property,const  ::wxString& text) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[4]),sipPySelf,SIP_NULLPTR,sipName_DrawValue);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::DrawValue(dc,rect,property,text);
        return;
    }

    extern void sipVH__propgrid_25(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxDC&,const  ::wxRect&, ::wxPGProperty*,const  ::wxString&);

    sipVH__propgrid_25(sipGILState, 0, sipPySelf, sipMeth, dc, rect, property, text);
}

bool sipwxPGChoiceEditor::OnEvent( ::wxPropertyGrid*propgrid, ::wxPGProperty*property, ::wxWindow*wnd_primary, ::wxEvent& event) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[5]),sipPySelf,SIP_NULLPTR,sipName_OnEvent);

    if (!sipMeth)
        return  ::wxPGChoiceEditor::OnEvent(propgrid,property,wnd_primary,event);

    extern bool sipVH__propgrid_26(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPropertyGrid*, ::wxPGProperty*, ::wxWindow*, ::wxEvent&);

    return sipVH__propgrid_26(sipGILState, 0, sipPySelf, sipMeth, propgrid, property, wnd_primary, event);
}

void sipwxPGChoiceEditor::SetValueToUnspecified( ::wxPGProperty*property, ::wxWindow*ctrl) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[6]),sipPySelf,SIP_NULLPTR,sipName_SetValueToUnspecified);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::SetValueToUnspecified(property,ctrl);
        return;
    }

    extern void sipVH__propgrid_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPGProperty*, ::wxWindow*);

    sipVH__propgrid_24(sipGILState, 0, sipPySelf, sipMeth, property, ctrl);
}

void sipwxPGChoiceEditor::SetControlAppearance( ::wxPropertyGrid*pg, ::wxPGProperty*property, ::wxWindow*ctrl,const  ::wxPGCell& appearance,const  ::wxPGCell& oldAppearance,bool unspecified) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[7]),sipPySelf,SIP_NULLPTR,sipName_SetControlAppearance);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::SetControlAppearance(pg,property,ctrl,appearance,oldAppearance,unspecified);
        return;
    }

    extern void sipVH__propgrid_28(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPropertyGrid*, ::wxPGProperty*, ::wxWindow*,const  ::wxPGCell&,const  ::wxPGCell&,bool);

    sipVH__propgrid_28(sipGILState, 0, sipPySelf, sipMeth, pg, property, ctrl, appearance, oldAppearance, unspecified);
}

void sipwxPGChoiceEditor::SetControlStringValue( ::wxPGProperty*property, ::wxWindow*ctrl,const  ::wxString& txt) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,SIP_NULLPTR,sipName_SetControlStringValue);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::SetControlStringValue(property,ctrl,txt);
        return;
    }

    extern void sipVH__propgrid_29(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPGProperty*, ::wxWindow*,const  ::wxString&);

    sipVH__propgrid_29(sipGILState, 0, sipPySelf, sipMeth, property, ctrl, txt);
}

void sipwxPGChoiceEditor::SetControlIntValue( ::wxPGProperty*property, ::wxWindow*ctrl,int value) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[9]),sipPySelf,SIP_NULLPTR,sipName_SetControlIntValue);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::SetControlIntValue(property,ctrl,value);
        return;
    }

    extern void sipVH__propgrid_30(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPGProperty*, ::wxWindow*,int);

    sipVH__propgrid_30(sipGILState, 0, sipPySelf, sipMeth, property, ctrl, value);
}

int sipwxPGChoiceEditor::InsertItem( ::wxWindow*ctrl,const  ::wxString& label,int index) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,SIP_NULLPTR,sipName_InsertItem);

    if (!sipMeth)
        return  ::wxPGChoiceEditor::InsertItem(ctrl,label,index);

    extern int sipVH__propgrid_31(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxWindow*,const  ::wxString&,int);

    return sipVH__propgrid_31(sipGILState, 0, sipPySelf, sipMeth, ctrl, label, index);
}

void sipwxPGChoiceEditor::DeleteItem( ::wxWindow*ctrl,int index) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[11]),sipPySelf,SIP_NULLPTR,sipName_DeleteItem);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::DeleteItem(ctrl,index);
        return;
    }

    extern void sipVH__propgrid_32(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxWindow*,int);

    sipVH__propgrid_32(sipGILState, 0, sipPySelf, sipMeth, ctrl, index);
}

void sipwxPGChoiceEditor::OnFocus( ::wxPGProperty*property, ::wxWindow*wnd) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[12]),sipPySelf,SIP_NULLPTR,sipName_OnFocus);

    if (!sipMeth)
    {
         ::wxPGChoiceEditor::OnFocus(property,wnd);
        return;
    }

    extern void sipVH__propgrid_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::wxPGProperty*, ::wxWindow*);

    sipVH__propgrid_24(sipGILState, 0, sipPySelf, sipMeth, property, wnd);
}

bool sipwxPGChoiceEditor::CanContainCustomImage() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[13]),sipPySelf,SIP_NULLPTR,sipName_CanContainCustomImage);

    if (!sipMeth)
        return  ::wxPGChoiceEditor::CanContainCustomImage();

    extern bool sipVH__propgrid_33(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH__propgrid_33(sipGILState, 0, sipPySelf, sipMeth);
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_CreateControls, "CreateControls(propgrid, property, pos, size) -> PGWindowList\n"
"\n"
"Instantiates editor controls.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_CreateControls(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_CreateControls(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPropertyGrid* propgrid;
         ::wxPGProperty* property;
        const  ::wxPoint* pos;
        int posState = 0;
        const  ::wxSize* size;
        int sizeState = 0;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_propgrid,
            sipName_property,
            sipName_pos,
            sipName_size,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8J1J1", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPropertyGrid, &propgrid, sipType_wxPGProperty, &property, sipType_wxPoint, &pos, &posState, sipType_wxSize, &size, &sizeState))
        {
             ::wxPGWindowList*sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::wxPGWindowList((sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::CreateControls(propgrid,property,*pos,*size) : sipCpp->CreateControls(propgrid,property,*pos,*size)));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::wxPoint *>(pos),sipType_wxPoint,posState);
            sipReleaseType(const_cast< ::wxSize *>(size),sipType_wxSize,sizeState);

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromNewType(sipRes,sipType_wxPGWindowList,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_CreateControls, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_UpdateControl, "UpdateControl(property, ctrl)\n"
"\n"
"Loads value from property to the control.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_UpdateControl(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_UpdateControl(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPGProperty* property;
         ::wxWindow* ctrl;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_property,
            sipName_ctrl,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPGProperty, &property, sipType_wxWindow, &ctrl))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::UpdateControl(property,ctrl) : sipCpp->UpdateControl(property,ctrl));
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_UpdateControl, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_OnEvent, "OnEvent(propgrid, property, wnd_primary, event) -> bool\n"
"\n"
"Handles events.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_OnEvent(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_OnEvent(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPropertyGrid* propgrid;
         ::wxPGProperty* property;
         ::wxWindow* wnd_primary;
         ::wxEvent* event;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_propgrid,
            sipName_property,
            sipName_wnd_primary,
            sipName_event,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8J8J9", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPropertyGrid, &propgrid, sipType_wxPGProperty, &property, sipType_wxWindow, &wnd_primary, sipType_wxEvent, &event))
        {
            bool sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::OnEvent(propgrid,property,wnd_primary,*event) : sipCpp->OnEvent(propgrid,property,wnd_primary,*event));
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            return PyBool_FromLong(sipRes);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_OnEvent, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_GetValueFromControl, "GetValueFromControl(variant, property, ctrl) -> bool\n"
"\n"
"Returns value from control, via parameter variant.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_GetValueFromControl(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_GetValueFromControl(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPGVariant* variant;
        int variantState = 0;
         ::wxPGProperty* property;
         ::wxWindow* ctrl;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_variant,
            sipName_property,
            sipName_ctrl,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ1J8J8", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPGVariant,&variant, &variantState, sipType_wxPGProperty, &property, sipType_wxWindow, &ctrl))
        {
            bool sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::GetValueFromControl(*variant,property,ctrl) : sipCpp->GetValueFromControl(*variant,property,ctrl));
            Py_END_ALLOW_THREADS
            sipReleaseType(variant,sipType_wxPGVariant,variantState);

            if (PyErr_Occurred())
                return 0;

            return PyBool_FromLong(sipRes);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_GetValueFromControl, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_SetValueToUnspecified, "SetValueToUnspecified(property, ctrl)\n"
"\n"
"Sets value in control to unspecified.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_SetValueToUnspecified(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_SetValueToUnspecified(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPGProperty* property;
         ::wxWindow* ctrl;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_property,
            sipName_ctrl,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPGProperty, &property, sipType_wxWindow, &ctrl))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::SetValueToUnspecified(property,ctrl) : sipCpp->SetValueToUnspecified(property,ctrl));
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_SetValueToUnspecified, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_GetName, "GetName() -> String\n"
"\n"
"Returns pointer to the name of the editor.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_GetName(PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_GetName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::wxPGChoiceEditor *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp))
        {
             ::wxString*sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::wxString((sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::GetName() : sipCpp->GetName()));
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromNewType(sipRes,sipType_wxString,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_GetName, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_SetControlIntValue, "SetControlIntValue(property, ctrl, value)\n"
"\n"
"Sets control's value specifically from int (applies to choice etc.).");

extern "C" {static PyObject *meth_wxPGChoiceEditor_SetControlIntValue(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_SetControlIntValue(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPGProperty* property;
         ::wxWindow* ctrl;
        int value;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_property,
            sipName_ctrl,
            sipName_value,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8i", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPGProperty, &property, sipType_wxWindow, &ctrl, &value))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::SetControlIntValue(property,ctrl,value) : sipCpp->SetControlIntValue(property,ctrl,value));
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_SetControlIntValue, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_SetControlStringValue, "SetControlStringValue(property, ctrl, txt)\n"
"\n"
"Sets control's value specifically from string.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_SetControlStringValue(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_SetControlStringValue(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxPGProperty* property;
         ::wxWindow* ctrl;
        const  ::wxString* txt;
        int txtState = 0;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_property,
            sipName_ctrl,
            sipName_txt,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8J1", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPGProperty, &property, sipType_wxWindow, &ctrl, sipType_wxString,&txt, &txtState))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::SetControlStringValue(property,ctrl,*txt) : sipCpp->SetControlStringValue(property,ctrl,*txt));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::wxString *>(txt),sipType_wxString,txtState);

            if (PyErr_Occurred())
                return 0;

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_SetControlStringValue, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_InsertItem, "InsertItem(ctrl, label, index) -> int\n"
"\n"
"Inserts item to existing control.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_InsertItem(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_InsertItem(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxWindow* ctrl;
        const  ::wxString* label;
        int labelState = 0;
        int index;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_ctrl,
            sipName_label,
            sipName_index,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J1i", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxWindow, &ctrl, sipType_wxString,&label, &labelState, &index))
        {
            int sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::InsertItem(ctrl,*label,index) : sipCpp->InsertItem(ctrl,*label,index));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::wxString *>(label),sipType_wxString,labelState);

            if (PyErr_Occurred())
                return 0;

            return SIPLong_FromLong(sipRes);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_InsertItem, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_DeleteItem, "DeleteItem(ctrl, index)\n"
"\n"
"Deletes item from existing control.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_DeleteItem(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_DeleteItem(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::wxWindow* ctrl;
        int index;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_ctrl,
            sipName_index,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8i", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxWindow, &ctrl, &index))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::DeleteItem(ctrl,index) : sipCpp->DeleteItem(ctrl,index));
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_DeleteItem, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_CanContainCustomImage, "CanContainCustomImage() -> bool\n"
"\n"
"Returns true if control itself can contain the custom image.");

extern "C" {static PyObject *meth_wxPGChoiceEditor_CanContainCustomImage(PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_CanContainCustomImage(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::wxPGChoiceEditor *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp))
        {
            bool sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp-> ::wxPGChoiceEditor::CanContainCustomImage() : sipCpp->CanContainCustomImage());
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            return PyBool_FromLong(sipRes);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_CanContainCustomImage, SIP_NULLPTR);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxPGChoiceEditor_CreateControlsBase, "CreateControlsBase(propgrid, property, pos, sz, extraStyle) -> wx.Window");

extern "C" {static PyObject *meth_wxPGChoiceEditor_CreateControlsBase(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxPGChoiceEditor_CreateControlsBase(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::wxPropertyGrid* propgrid;
         ::wxPGProperty* property;
        const  ::wxPoint* pos;
        int posState = 0;
        const  ::wxSize* sz;
        int szState = 0;
        long extraStyle;
        const  ::wxPGChoiceEditor *sipCpp;

        static const char *sipKwdList[] = {
            sipName_propgrid,
            sipName_property,
            sipName_pos,
            sipName_sz,
            sipName_extraStyle,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ8J8J1J1l", &sipSelf, sipType_wxPGChoiceEditor, &sipCpp, sipType_wxPropertyGrid, &propgrid, sipType_wxPGProperty, &property, sipType_wxPoint, &pos, &posState, sipType_wxSize, &sz, &szState, &extraStyle))
        {
             ::wxWindow*sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->CreateControlsBase(propgrid,property,*pos,*sz,extraStyle);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::wxPoint *>(pos),sipType_wxPoint,posState);
            sipReleaseType(const_cast< ::wxSize *>(sz),sipType_wxSize,szState);

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromType(sipRes,sipType_wxWindow,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_PGChoiceEditor, sipName_CreateControlsBase, SIP_NULLPTR);

    return SIP_NULLPTR;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_wxPGChoiceEditor(void *, const sipTypeDef *);}
static void *cast_wxPGChoiceEditor(void *sipCppV, const sipTypeDef *targetType)
{
     ::wxPGChoiceEditor *sipCpp = reinterpret_cast< ::wxPGChoiceEditor *>(sipCppV);

    if (targetType == sipType_wxPGEditor)
        return static_cast< ::wxPGEditor *>(sipCpp);

    if (targetType == sipType_wxObject)
        return static_cast< ::wxObject *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxPGChoiceEditor(void *, int);}
static void release_wxPGChoiceEditor(void *sipCppV, int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipwxPGChoiceEditor *>(sipCppV);
    else
        delete reinterpret_cast< ::wxPGChoiceEditor *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void *array_wxPGChoiceEditor(Py_ssize_t);}
static void *array_wxPGChoiceEditor(Py_ssize_t sipNrElem)
{
    return new  ::wxPGChoiceEditor[sipNrElem];
}


extern "C" {static void assign_wxPGChoiceEditor(void *, SIP_SSIZE_T, void *);}
static void assign_wxPGChoiceEditor(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::wxPGChoiceEditor *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::wxPGChoiceEditor *>(sipSrc);
}


extern "C" {static void *copy_wxPGChoiceEditor(const void *, SIP_SSIZE_T);}
static void *copy_wxPGChoiceEditor(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::wxPGChoiceEditor(reinterpret_cast<const  ::wxPGChoiceEditor *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_wxPGChoiceEditor(sipSimpleWrapper *);}
static void dealloc_wxPGChoiceEditor(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipwxPGChoiceEditor *>(sipGetAddress(sipSelf))->sipPySelf = SIP_NULLPTR;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_wxPGChoiceEditor(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_wxPGChoiceEditor(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_wxPGChoiceEditor(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipwxPGChoiceEditor *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxPGChoiceEditor();
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
            {
                delete sipCpp;
                return SIP_NULLPTR;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::wxPGChoiceEditor* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_wxPGChoiceEditor, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxPGChoiceEditor(*a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_wxPGChoiceEditor[] = {{37, 255, 1}};


static PyMethodDef methods_wxPGChoiceEditor[] = {
    {SIP_MLNAME_CAST(sipName_CanContainCustomImage), meth_wxPGChoiceEditor_CanContainCustomImage, METH_VARARGS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_CanContainCustomImage)},
    {SIP_MLNAME_CAST(sipName_CreateControls), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_CreateControls), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_CreateControls)},
    {SIP_MLNAME_CAST(sipName_CreateControlsBase), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_CreateControlsBase), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_CreateControlsBase)},
    {SIP_MLNAME_CAST(sipName_DeleteItem), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_DeleteItem), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_DeleteItem)},
    {SIP_MLNAME_CAST(sipName_GetName), meth_wxPGChoiceEditor_GetName, METH_VARARGS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_GetName)},
    {SIP_MLNAME_CAST(sipName_GetValueFromControl), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_GetValueFromControl), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_GetValueFromControl)},
    {SIP_MLNAME_CAST(sipName_InsertItem), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_InsertItem), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_InsertItem)},
    {SIP_MLNAME_CAST(sipName_OnEvent), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_OnEvent), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_OnEvent)},
    {SIP_MLNAME_CAST(sipName_SetControlIntValue), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_SetControlIntValue), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_SetControlIntValue)},
    {SIP_MLNAME_CAST(sipName_SetControlStringValue), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_SetControlStringValue), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_SetControlStringValue)},
    {SIP_MLNAME_CAST(sipName_SetValueToUnspecified), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_SetValueToUnspecified), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_SetValueToUnspecified)},
    {SIP_MLNAME_CAST(sipName_UpdateControl), SIP_MLMETH_CAST(meth_wxPGChoiceEditor_UpdateControl), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxPGChoiceEditor_UpdateControl)}
};

sipVariableDef variables_wxPGChoiceEditor[] = {
    {PropertyVariable, sipName_Name, &methods_wxPGChoiceEditor[4], SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
};

PyDoc_STRVAR(doc_wxPGChoiceEditor, "PGChoiceEditor()");


sipClassTypeDef sipTypeDef__propgrid_wxPGChoiceEditor = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_wxPGChoiceEditor,
        {SIP_NULLPTR},
        SIP_NULLPTR
    },
    {
        sipNameNr_PGChoiceEditor,
        {0, 0, 1},
        12, methods_wxPGChoiceEditor,
        0, SIP_NULLPTR,
        1, variables_wxPGChoiceEditor,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_wxPGChoiceEditor,
    -1,
    -1,
    supers_wxPGChoiceEditor,
    SIP_NULLPTR,
    init_type_wxPGChoiceEditor,
    SIP_NULLPTR,
    SIP_NULLPTR,
#if PY_MAJOR_VERSION >= 3
    SIP_NULLPTR,
    SIP_NULLPTR,
#else
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
#endif
    dealloc_wxPGChoiceEditor,
    assign_wxPGChoiceEditor,
    array_wxPGChoiceEditor,
    copy_wxPGChoiceEditor,
    release_wxPGChoiceEditor,
    cast_wxPGChoiceEditor,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
