
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-27T07:51:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9210e7f2944d15ad56c44d0d7d4a5788c7730ce",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
