from django.conf import settings

DJANGO_MAILCENTER_AUTO_REGISTER_MODELS = getattr(settings, "DJANGO_MAILCENTER_AUTO_REGISTER_MODELS", True)
DJANGO_MAILCENTER_AUTO_REGISTER_ADMINS = getattr(settings, "DJANGO_MAILCENTER_AUTO_REGISTER_ADMINS", True)
DJANGO_MAILCENTER_APP_LABEL = getattr(settings, "DJANGO_MAILCENTER_APP_LABEL", "django_mailcenter")

DJANGO_MAILCETNER_API_SERVER = getattr(settings, "DJANGO_MAILCETNER_API_SERVER", None)