
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-23T12:56:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "23ebe0be259491a3d80800c320de823a782f3c52",
 "version": "0.4.126"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
