
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-25T23:00:40-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "edd9955301edf4edf2327c26f7f86681adc0ab4d",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
