# Generated by Django 2.2.14 on 2020-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200712_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='sharing',
            field=models.CharField(choices=[('personal', 'personal'), ('shared', 'shared')], max_length=8),
        ),
    ]
