# Generated by Django 2.2.14 on 2020-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200712_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='sharing',
            field=models.CharField(choices=[('personal', 'personal'), ('shared', 'shared')], default='shared', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=7),
        ),
    ]
