depends = ('ITKPyBase', 'ITKIOImageBase', )
templates = (
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('LabelSetDilateImageFilter', 'itk::LabelSetDilateImageFilter', 'itkLabelSetDilateImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('LabelSetErodeImageFilter', 'itk::LabelSetErodeImageFilter', 'itkLabelSetErodeImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterISS2TRUEISS2', True, 'itk::Image< signed short,2 >,true,itk::Image< signed short,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterISS2FALSEISS2', True, 'itk::Image< signed short,2 >,false,itk::Image< signed short,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUC2TRUEIUC2', True, 'itk::Image< unsigned char,2 >,true,itk::Image< unsigned char,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUC2FALSEIUC2', True, 'itk::Image< unsigned char,2 >,false,itk::Image< unsigned char,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUS2TRUEIUS2', True, 'itk::Image< unsigned short,2 >,true,itk::Image< unsigned short,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUS2FALSEIUS2', True, 'itk::Image< unsigned short,2 >,false,itk::Image< unsigned short,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIF2TRUEIF2', True, 'itk::Image< float,2 >,true,itk::Image< float,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIF2FALSEIF2', True, 'itk::Image< float,2 >,false,itk::Image< float,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterID2TRUEID2', True, 'itk::Image< double,2 >,true,itk::Image< double,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterID2FALSEID2', True, 'itk::Image< double,2 >,false,itk::Image< double,2 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterISS3TRUEISS3', True, 'itk::Image< signed short,3 >,true,itk::Image< signed short,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterISS3FALSEISS3', True, 'itk::Image< signed short,3 >,false,itk::Image< signed short,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUC3TRUEIUC3', True, 'itk::Image< unsigned char,3 >,true,itk::Image< unsigned char,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUC3FALSEIUC3', True, 'itk::Image< unsigned char,3 >,false,itk::Image< unsigned char,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUS3TRUEIUS3', True, 'itk::Image< unsigned short,3 >,true,itk::Image< unsigned short,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIUS3FALSEIUS3', True, 'itk::Image< unsigned short,3 >,false,itk::Image< unsigned short,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIF3TRUEIF3', True, 'itk::Image< float,3 >,true,itk::Image< float,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterIF3FALSEIF3', True, 'itk::Image< float,3 >,false,itk::Image< float,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterID3TRUEID3', True, 'itk::Image< double,3 >,true,itk::Image< double,3 >'),
  ('LabelSetMorphBaseImageFilter', 'itk::LabelSetMorphBaseImageFilter', 'itkLabelSetMorphBaseImageFilterID3FALSEID3', True, 'itk::Image< double,3 >,false,itk::Image< double,3 >'),
)
snake_case_functions = ('label_set_dilate_image_filter', 'label_set_erode_image_filter', 'label_set_morph_base_image_filter', )
