# -*- coding: utf-8 -*-

"""
    aws_apimatic

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ConditionEnum(object):

    """Implementation of the 'Condition' enum.

    TODO: type enum description here.

    Attributes:
        ALL: TODO: type description here.
        NEW: TODO: type description here.
        USED: TODO: type description here.
        COLLECTIBLE: TODO: type description here.
        REFURBISHED: TODO: type description here.

    """

    ALL = 'All'

    NEW = 'New'

    USED = 'Used'

    COLLECTIBLE = 'Collectible'

    REFURBISHED = 'Refurbished'

