# -*- coding: utf-8 -*-

"""
    aws_apimatic

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import aws_apimatic.models.summary

class Promotion(object):

    """Implementation of the 'Promotion' model.

    TODO: type model description here.

    Attributes:
        summary (Summary): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "summary":'Summary'
    }

    def __init__(self,
                 summary=None):
        """Constructor for the Promotion class"""

        # Initialize members of the class
        self.summary = summary


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        summary = aws_apimatic.models.summary.Summary.from_dictionary(dictionary.get('Summary')) if dictionary.get('Summary') else None

        # Return an object of this model
        return cls(summary)


