# -*- coding: utf-8 -*-

"""
    aws_apimatic

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import aws_apimatic.models.similar_product

class SimilarProducts(object):

    """Implementation of the 'SimilarProducts' model.

    TODO: type model description here.

    Attributes:
        similar_product (list of SimilarProduct): TODO: type description
            here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "similar_product":'SimilarProduct'
    }

    def __init__(self,
                 similar_product=None):
        """Constructor for the SimilarProducts class"""

        # Initialize members of the class
        self.similar_product = similar_product


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        similar_product = None
        if dictionary.get('SimilarProduct') != None:
            similar_product = list()
            for structure in dictionary.get('SimilarProduct'):
                similar_product.append(aws_apimatic.models.similar_product.SimilarProduct.from_dictionary(structure))

        # Return an object of this model
        return cls(similar_product)


