# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapython
from giteapython.models.create_pull_review_comment import CreatePullReviewComment  # noqa: E501
from giteapython.rest import ApiException


class TestCreatePullReviewComment(unittest.TestCase):
    """CreatePullReviewComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePullReviewComment(self):
        """Test CreatePullReviewComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapython.models.create_pull_review_comment.CreatePullReviewComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
