# Generated by Django 2.2.16 on 2020-10-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_subscription', '0008_member_servicesattestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoldp_subscription.Gendermember'),
        ),
        migrations.AlterField(
            model_name='member',
            name='typemember',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoldp_subscription.Typemember', verbose_name='Type of member'),
        ),
    ]
