# Generated by Django 2.2.4 on 2019-11-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('default', models.BooleanField(default=False, unique=True)),
                ('default_groups', models.ManyToManyField(blank=True, null=True, related_name='default_groups', to='auth.Group')),
                ('enabling_groups', models.ManyToManyField(blank=True, null=True, related_name='enabling_groups', to='auth.Group')),
                ('qualifying_groups', models.ManyToManyField(related_name='qualifying_groups', to='auth.Group')),
            ],
        ),
    ]
