# Generated by Django 2.2.1 on 2019-05-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_mediabrowser', '0004_mediaimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='thumbnail',
        ),
    ]
