from . import objects
events = objects.events()


def setEventType(name, value):
    value = str(value).upper()

    global events
    setattr(events, name, objects.event(value))
    events.list.append(name)


setEventType("MESSAGE_NEW", ":::CANARYBOT:MESSAGE_NEW:::")
setEventType("MESSAGE_ALLOW", ":::CANARYBOT:MESSAGE_ALLOW:::")
setEventType("MESSAGE_DENY", ":::CANARYBOT:MESSAGE_DENY:::")
setEventType("MESSAGE_EVENT", ":::CANARYBOT:MESSAGE_EVENT:::")

setEventType("PHOTO_NEW", ":::CANARYBOT:PHOTO_NEW:::")
setEventType("PHOTO_COMMENT_NEW", ":::CANARYBOT:PHOTO_COMMENT_NEW:::")
setEventType("PHOTO_COMMENT_EDIT", ":::CANARYBOT:PHOTO_COMMENT_EDIT:::")
setEventType("PHOTO_COMMENT_RESTORE", ":::CANARYBOT:PHOTO_COMMENT_RESTORE:::")
setEventType("PHOTO_COMMENT_DELETE", ":::CANARYBOT:PHOTO_COMMENT_DELETE:::")

setEventType("AUDIO_NEW", ":::CANARYBOT:AUDIO_NEW:::")

setEventType("VIDEO_NEW", ":::CANARYBOT:VIDEO_NEW:::")
setEventType("VIDEO_COMMENT_NEW", ":::CANARYBOT:VIDEO_COMMENT_NEW:::")
setEventType("VIDEO_COMMENT_EDIT", ":::CANARYBOT:VIDEO_COMMENT_EDIT:::")
setEventType("VIDEO_COMMENT_RESTORE", ":::CANARYBOT:VIDEO_COMMENT_RESTORE:::")
setEventType("VIDEO_COMMENT_DELETE", ":::CANARYBOT:VIDEO_COMMENT_DELETE:::")

setEventType("WALL_POST_NEW", ":::CANARYBOT:WALL_POST_NEW:::")
setEventType("WALL_REPOST", ":::CANARYBOT:WALL_REPOST:::")
setEventType("WALL_REPLY_NEW", ":::CANARYBOT:WALL_REPLY_NEW:::")
setEventType("WALL_REPLY_EDIT", ":::CANARYBOT:WALL_REPLY_EDIT:::")
setEventType("WALL_REPLY_RESTORE", ":::CANARYBOT:WALL_REPLY_RESTORE:::")
setEventType("WALL_REPLY_DELETE", ":::CANARYBOT:WALL_REPLY_DELETE:::")

setEventType("BOARD_POST_NEW", ":::CANARYBOT:BOARD_POST_NEW:::")
setEventType("BOARD_POST_EDIT", ":::CANARYBOT:BOARD_POST_EDIT:::")
setEventType("BOARD_POST_RESTORE", ":::CANARYBOT:BOARD_POST_RESTORE:::")
setEventType("BOARD_POST_DELETE", ":::CANARYBOT:BOARD_POST_DELETE:::")

setEventType("MARKET_COMMENT_NEW", ":::CANARYBOT:MARKET_COMMENT_NEW:::")
setEventType("MARKET_COMMENT_EDIT", ":::CANARYBOT:MARKET_COMMENT_EDIT:::")
setEventType("MARKET_COMMENT_RESTORE", ":::CANARYBOT:MARKET_COMMENT_RESTORE:::")
setEventType("MARKET_COMMENT_DELETE", ":::CANARYBOT:MARKET_COMMENT_DELETE:::")
setEventType("MARKET_ORDER_NEW", ":::CANARYBOT:MARKET_ORDER_NEW::::::")
setEventType("MARKET_ORDER_EDIT", ":::CANARYBOT:MARKET_ORDER_EDIT::::::")

setEventType("GROUP_LEAVE", ":::CANARYBOT:GROUP_LEAVE:::")
setEventType("GROUP_JOIN", ":::CANARYBOT:GROUP_JOIN:::")

setEventType("USER_BLOCK", ":::CANARYBOT:USER_BLOCK:::")
setEventType("USER_UNBLOCK", ":::CANARYBOT:USER_UNBLOCK:::")

setEventType("POLL_VOTE_NEW", ":::CANARYBOT:POLL_VOTE_NEW:::")

setEventType("GROUP_OFFICERS_EDIT", ":::CANARYBOT:GROUP_OFFICERS_EDIT:::")
setEventType("GROUP_CHANGE_SETTINGS", ":::CANARYBOT:GROUP_CHANGE_SETTINGS:::")
setEventType("GROUP_CHANGE_PHOTO", ":::CANARYBOT:GROUP_CHANGE_PHOTO:::")

setEventType("VKPAY_TRANSACTION", ":::CANARYBOT:VKPAY_TRANSACTION:::")
setEventType("APP_PAYLOAD", ":::CANARYBOT:APP_PAYLOAD::::::")

setEventType("LIKE_ADD", ":::CANARYBOT:LIKEADD::::::")
setEventType("LIKE_REMOVE", ":::CANARYBOT:LIKEREMOVE::::::")