__title__ = 'melenium'
__description__ = 'Routine automation.'
__url__ = 'https://github.com/a-maliarov/melenium'
__version__ = '0.1.0'
__author__ = 'Anatolii Maliarov'
__author_email__ = 'tly.mov@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Anatolii Maliarov'
