MAJOR_VERSION = 0
MINOR_VERSION = 3
PATCH_VERSION = 9
VERSION = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)


__all__ = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'VERSION']
